### ISSUE TITLE
Trying to use one function of mjlib

### ISSUE THREAD

**Issue by mjm522** [openai/mujoco-py#12]
Hi, 

I have doubt, can anyone please help?

I want to use the mj_fullM function of mjlib. (line 172 and 173). This is commented. So in my forked version of mujoco-py, I tried to add a wrapper for same as follows:

Line 172 and 173 in mjlib
```
mjlib.mj_fullM.argtypes = [POINTER(MJMODEL), POINTER(c_double), POINTER(c_double)]
mjlib.mj_fullM.restype = None
```

in mjcore.py

```
def fullM(self):
        array_length = self.nv*self.nv*100
        fullqM = np.zeros((array_length))
        mjlib.mj_fullM(self.ptr, fullqM.astype(np.double).ctypes.data_as(POINTER(c_double)), self.data.qM.astype(np.double).ctypes.data_as(POINTER(c_double)))
        return fullqM
```
But on calling in my main:

`myObj.model.fullM()`, I get back just a **bunch of zeros**. While `myObj.model.data.qM` does have the values in it.

In the mujoco library the mj_fullM function converts the reduced inertia matrix to the complete inertia matrix.

What am I doing wrong? Any suggestion?

**Comment by tlbtlbtlb** [comment]
The call to `.astype(np.double)` makes a copy  , even if the underlying type is already double. [[doc](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html)]. Eliminate the `.astype(np.double)`, and be sure the type is correct by specifying it in the `np.zeros` call. Something like: 

```python
    fullqM = np.zeros((array_length,), dtype=np.double)
    mjlib.mj_fullM(self.ptr, fullqM.ctypes.data_as(POINTER(c_double)), self.data.qM.astype(np.double).ctypes.data_as(POINTER(c_double)))
```
