### ISSUE TITLE
Error message in config.py

### ISSUE THREAD

**Issue by noahmacaulay** [openai/mujoco-py#15]
The error message in config.py for missing binaries and keys reads: 
'To use MuJoCo, you need to either populate ~/.mujoco/mjkey.txt and ~/.mujco/mjpro131, or set the MUJOCO_PY_MJKEY_PATH and MUJOCO_PY_MJPRO_PATH environment variables appropriately. Follow the instructions on https://github.com/openai/mujoco-py for where to obtain these.'
But it should read:
'To use MuJoCo, you need to either populate ~/.mujoco/mjkey.txt and ~/.mujoco/mjpro131, or set the MUJOCO_PY_MJKEY_PATH and MUJOCO_PY_MJPRO_PATH environment variables appropriately. Follow the instructions on https://github.com/openai/mujoco-py for where to obtain these.'

(The difference is that the first says '~/.mujco/mjpro131' but it should say '~./mujoco/mjpro131')

**Comment by tlbtlbtlb** [comment]
Thanks!
