### ISSUE TITLE
Bus error (core dumped) on rendering

### ISSUE THREAD

**Issue by aravind0706** [openai/mujoco-py#173]
Installed MJC 1.5 on a GPU Ubuntu 16.04 machine. On trying to render from sim for obtaining image input, I end up with Bus error (core dumped).

```
sim.render(height=240, width=240)
Found 4 GPUs for rendering. Using device 0.
Bus error (core dumped)
```

Edit 1: If there's an option / way to force rendering on CPU even on machines with GPU, that would be helpful. The GPUs are needed in my code for running convnets, not really for fast / high-end graphics rendering.

Edit 2: Verified that it works on another Ubuntu 16.04 machine with 3 GPUs without having to do any changes. Any pointers to what specific issue on the machine is causing this?

**Comment by foolyc** [comment]
Well, you can edit the builder.py to CPU render, that is 
`
elif sys.platform == 'linux':
if get_nvidia_lib_dir() is not None and os.getenv('MUJOCO_PY_FORCE_CPU') is None:
     Builder = LinuxGPUExtensionBuilder
else:
     Builder = LinuxCPUExtensionBuilder
`
change to 
`
Builder = LinuxCPUExtensionBuilder
`

**Comment by aravind0706** [comment]
Thanks! This works
