### ISSUE TITLE
Corrupted installation: error code 7

### ISSUE THREAD

**Issue by koenhelwegen** [openai/mujoco-py#200]
After getting the mujoco license and binaries, I tried installing with `python3 -m pip install --user mujoco-py`. Installation seemed to freeze (twice). I now see this is more common, I should install from source instead.

However, it seems I corrupted something in my first attempt. I now receive an error code -7 when trying to install (also if I install from source). Additionally, if I try to import the gym module in a python script or console, I receive an error code 7: SIGEMT. According to google, this has something to do with an emulator trap, but I'm not sure what that means. 

I tried restarting, clearing my /tmp/ folder, and reinstalling gym via pip, but I keep getting this error. Any clue how I resolve this?

Here is the full error message when trying to install mujoco in pip:

> Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cetq2m19/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pu_rnjde-record/install-record.txt --single-version-externally-managed --compile" failed with error code -7 in /tmp/pip-build-cetq2m19/mujoco-py/

**Comment by kghelwegen** [comment]
I have now figured out how to install gym and the latest version of mujoco-py (from source) in a virtual environment. So I'm starting to see why virtual environments are considered best practice ;) If anyone has a clue how to fix the gym module on my main python path, please let me know

**Comment by koenhelwegen** [comment]
Closing as this was probably a problem in my local setup.
