### ISSUE TITLE
Is there and equivalent to "simulate.cpp" in Mujoco-Py?

### ISSUE THREAD

**Issue by kaelgabriel** [openai/mujoco-py#248]
Hi there guys!

Is there an equivalent to the code simulate.cpp, generally located in ~/.mujoco/mujocopro151/sample (or the binary on /bin) in mujoco-py?

It would be nice to be able to change features in the simulation while the training model is in the "test phase", something like V-REP.

Thanks for your time.

**Comment by machinaut** [comment]
@kaelgabriel you can change the simulation while it is running, but there is not a specially-made interactive user program written with mujoco-py that I know of.

You can re-implement simulate.cpp yourself using the `mujoco_py.functions` object to access internal functions, and manually use `ctypes` objects (including pointers, etc) where the interfaces require C-type data structures.

I'd be interested in reviewing a pull request for an example of this if one was provided.

Closing for now, as I think the question is answered.
