### ISSUE TITLE
AttributeError: function 'mjv_makeObjects' not found

### ISSUE THREAD

**Issue by aqeelanwar** [openai/mujoco-py#251]
Hello,
I am trying to set up Mujoco for one of my projects. I installed all the dependencies and used the appropriate license file. When I am trying to run an existing code, its giving me the following error

> 
> func = self._FuncPtr((name_or_ordinal, self))
> AttributeError: function 'mjv_makeObjects' not found

when I try to use

> mjlib.mjv_makeObjects.argtypes = [POINTER(MJVOBJECTS), c_int]

. Does anyone know if it is the installation issue or am I missing something? The examples provided by the mujoco_py repositories are working without any error though.

**Comment by jonashen** [comment]
+1

**Comment by kirk86** [comment]
same issue

**Comment by bohan-zhang** [comment]
+1

**Comment by machinaut** [comment]
This is unfortunately code that only works with the older (previous) version of mujoco-py.

If you downgrade and install the proper version of mujoco, this should work.

We're pretty limited in what we can support, so we're only supporting a single version (mujoco150) right now.

**Comment by puranjayr96** [comment]
Are there any alternatives for this in mjpro150?
