### ISSUE TITLE
Mujoco_py support for latest GCC compiler

### ISSUE THREAD

**Issue by JulianYG** [openai/mujoco-py#254]
In mujoco_py/builder.py  line 302, in _build_impl 'Could not find GCC 6 or GCC 7 executable.\n\n'
RuntimeError: Could not find GCC 6 or GCC 7 executable.
Since I've updated my gcc to 8.1.0.

**Comment by TCtobychen** [comment]
same issue

**Comment by cassanolucas** [comment]
Same issue. Any known solutions?

**Comment by TeaPearce** [comment]
snap

**Comment by JulianYG** [comment]
I solved it by copying out the error commands and manually forcing it to use another gcc 7 compiler. However, it would be great if we can have gcc 8 support, thanks!

**Comment by iandanforth** [comment]
Another work around on OSX is to use brew to install another version of GCC

`brew install gcc@6`

This worked for me with other versions installed as well. Note gcc@7 did not work immediately so I went with 6.

**Comment by arpit15** [comment]
To add support for gcc 8 change [this](url
https://github.com/openai/mujoco-py/blob/master/mujoco_py/builder.py#L294) line to
```python
c_compilers = ['/usr/local/bin/gcc-6', '/usr/local/bin/gcc-7','/usr/local/bin/gcc-8']
``` 
@JulianYG @TCtobychen @cassanolucas @TeaPearce

**Comment by pavyedav** [comment]
At @arpit15 , what were the steps you took after adding gcc-8 to c_compilers? I still get the error: 

`>>> import mujoco_py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/mujoco_py/__init__.py", line 1, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/usr/local/lib/python3.6/site-packages/mujoco_py/builder.py", line 468, in <module>
    cymj = load_cython_ext(mjpro_path)
  File "/usr/local/lib/python3.6/site-packages/mujoco_py/builder.py", line 90, in load_cython_ext
    cext_so_path = builder.build()
  File "/usr/local/lib/python3.6/site-packages/mujoco_py/builder.py", line 202, in build
    built_so_file_path = self._build_impl()
  File "/usr/local/lib/python3.6/site-packages/mujoco_py/builder.py", line 302, in _build_impl
    'Could not find GCC 6 or GCC 7 executable.\n\n'
RuntimeError: Could not find GCC 6 or GCC 7 executable.`

Seems like I need to do something (like a compile) after saving that change.

**Comment by phaniram-sayapaneni** [comment]
brew install gcc@6
or
brew install gcc@7

pip uninstall mujoco_py
pip install mujoco_py


Did not work for me, any suggestions please? I get the following error:
istutils.errors.CompileError: command '/usr/local/bin/gcc-6' failed with exit status 1

**Comment by phaniram-sayapaneni** [comment]
Also tried to set the compilers to gcc-8
Still getting the error:
CompileError: command '/usr/local/bin/gcc-8' failed with exit status 1

**Comment by machinaut** [comment]
Merged a fix to this, latest mujoco-py works with latest homebrew GCC!

**Comment by phaniram-sayapaneni** [comment]
Great!

Thanks a lot!!

**Comment by ali-chaudhry8** [comment]
Hi, I am getting this error: 
"distutils.errors.CompileError: command '/usr/local/bin/gcc-6' failed with exit status 1"
Tried re installing Mujoco, installed GCC7 and 8, but this issue persists. Please help...

**Comment by marjanin** [comment]
> Hi, I am getting this error:
> "distutils.errors.CompileError: command '/usr/local/bin/gcc-6' failed with exit status 1"
> Tried re installing Mujoco, installed GCC7 and 8, but this issue persists. Please help...

Hi,
I am getting the same error on Mac. Did you find a solution?

**Comment by marjanin** [comment]
It worked once I installed the pkg mentioned here:
https://stackoverflow.com/questions/51274905/brew-install-on-mojave

**Comment by dmalpica** [comment]
It's August 2019. Had this issue with gcc-9

brew install gcc@8 worked for me

**Comment by newuhe** [comment]
> To add support for gcc 8 change [this](https://github.com/openai/mujoco-py/blob/master/mujoco_py/builder.py#L294) line to
> 
> ```python
> c_compilers = ['/usr/local/bin/gcc-6', '/usr/local/bin/gcc-7','/usr/local/bin/gcc-8']
> ```
> 
> @JulianYG @TCtobychen @cassanolucas @TeaPearce

this works for me, gcc9

**Comment by emimarz** [comment]
same issue gcc 9
RuntimeError: Could not find GCC executable.

**Comment by imrancharania** [comment]
Using gcc 8 seems to have resolved this issue for me.

**Comment by wookayin** [comment]
Another workaround (perhaps most the easiest solution) is to use `CC` environment variable. (see #651 as well)

```
export CC=/usr/local/bin/gcc-11 
python -c "import mujoco_py"     # to initiate Cython build_ext
```
