### ISSUE TITLE
mujoco_py.PyMjData.act not writable

### ISSUE THREAD

**Issue by slurye** [openai/mujoco-py#266]
I want to program custom actuator dynamics for biological muscles but when I attempt to access sim.data.a ct, like accessing sim.data.ctrl, the error says "attribute not writable." Is this a bug or am I not understanding something fundamental about the attribute?

**Comment by machinaut** [comment]
Where is the code that is doing this?

`sim.data.ctrl` is the control for the actuators in the simulation.

**Comment by machinaut** [comment]
Looks like to me that this is a Mujoco 2.0 feature, so closing this in lieu of #303 

Right now we're just focusing on 1.50, but we know that 2.0 has a bunch of new features.
