### ISSUE TITLE
Segmentation fault when creating window glfw

### ISSUE THREAD

**Issue by tianheyu927** [openai/mujoco-py#272]
When I run `python -c "import gym; env = gym.make('Humanoid-v2'); env.render()"` with mujoco 1.50, it shows the following error:
```
Creating window glfw
Segmentation fault (core dumped)
```

I use gdb to debug this and get the following messages:
```
Creating window glfw

Program received signal SIGSEGV, Segmentation fault.
0x00007fffefd4228e in glGetString () from /usr/lib/x86_64-linux-gnu/libOSMesa.so.6
```

However, it does works well when I try ./simulate in the ./mujoco/mjpro150/bin
Does anyone know how to fix this issue? I have Ubuntu 14.04, python 3.5.2 and have updated the latest OpenGL library.

**Comment by yxnyxnyxnyxn** [comment]
i have the same problem, have you solved that?

**Comment by tianheyu927** [comment]
This [thread](https://github.com/openai/mujoco-py/pull/145) could be helpful.
