### ISSUE TITLE
Speeding up Rendering

### ISSUE THREAD

**Issue by bhairavmehta95** [openai/mujoco-py#277]
Is there a good way to render MuJoCo images (i.e an image of the environment) fast / What's the fastest way to render?

I am trying to get a speed up in rendering (goal is to collect more data) by spawning multiple environments, but when I test a single environment worker and multiple environment workers, I see a performance decrease in speed.

```python

import time
st = time.time()
env = gym.make(env_id)
env.reset()
for i in range(3000):
    action = env.action_space.sample()
    obs, rewards, dones, info = env.step(action)
    env.render(mode='rgb_array')
    if dones:
        env.reset()

print(time.time() - st)
```

Gives me about 15s to render 3000 frames, where as an MPI enabled version, (3 MPI workers, using `SubprocVecEnv`) is taking longer (~24s to render the same 3000 frames).

Is there any way I can boost the speed at which frames get rendered?

**Comment by machinaut** [comment]
This is a _really_ hard question.

I think the best things to do are probably the most generic performance measurements: e.g. figure out what resources your processes are limited by (CPU, GPU, memory bandwith, etc), and try to find ways to relieve those limits.

Specifically to this, maybe make sure the rendering is happening using the right OpenGL libraries.

Also you can make data faster by rendering smaller images.

I'm not sure what is actionable here other than making these suggestions.  This project is a python wrapper to mujoco -- but the faster option would be compiling a binary against the mujoco library directly.  Even faster might be not using mujoco's renderer and using a different renderer (or writing your own).
