### ISSUE TITLE
Setting a maximum velocity for a joint

### ISSUE THREAD

**Issue by febert** [openai/mujoco-py#30]
Hi,

is it possible to set a maximum velocity for a joint, similarly to the "maxvel" property in earlier mujoco versions?
Directly setting the velocity data field does not work since it is write-protected.

**Comment by WilsonWangTHU** [comment]
hi,

i guess you could try this trick
#https://github.com/openai/gym/issues/234

**Comment by machinaut** [comment]
model parameters are now read-write!

Though this does not mean the underlying physics simulation will respect dynamically-adjusted parameters.

I'd recommend comparing the results of dynamically changing parameters, and re-loading XML, to ensure you get sufficiently similar behavior.
