### ISSUE TITLE
TypeError:'numpy.int32' object is not iterable when 'gym.make('HandReach-v0')'

### ISSUE THREAD

**Issue by LiDuan1111** [openai/mujoco-py#304]

**Comment by chrisole** [comment]
Have u resolve it?

**Comment by machinaut** [comment]
@LiDuan1111 could you describe what situation the error occurred in, and provide more of the error message?

Closing for now, but reopen when there is more info.

**Comment by aaronsnoswell** [comment]
Duplicate of #324.
