### ISSUE TITLE
How to calculate the contact force?

### ISSUE THREAD

**Issue by WuXinyang2012** [openai/mujoco-py#325]
Hi, by checking mujoco documentation, I found that it supports a function mj_contactForce() to directly output the 6D contact force. 
And with your API mujoco_py.MjSim I can access the mujoco's mjModel and mjData variables. However, it seems that they do not directly contain the force information.
In my understanding, I calculate the contact force in this way:

```python
for i in range(mjData.ncon):
    print(' Contact force on geom2', mjData.cfrc_ext[mjModel.geom_bodyid[mjData.contact[i].geom2]])
```
But I am not sure if this calculation is right. I mainly try to first locate the body of the collision geom, and extract the external force on that body. Do I need some more calculation on it?

Thanks in advance!

**Comment by machinaut** [comment]
Internal functions can be accessed with `mujoco_py.functions` though not every one is present, and using C-style pointers via arrays is complicated.

I updated this small example to demonstrate this. https://gist.github.com/machinaut/209c44e8c55245c0d0f0094693053158

As for whether this is the value you want or not, and how this is being calculated, these are better questions for the MuJoCo forums  http://www.mujoco.org/forum/index.php
