### ISSUE TITLE
assertion (not done) error in an edited humanoidstandup environment

### ISSUE THREAD

**Issue by gkcgvn** [openai/mujoco-py#367]
Hi, I modified the humanoidstandup-v2, and I would like to stop the episode when some of the conditions (like stepping) are satisfied. For this reason, I placed a done condition instead of built-in done= False inside step function. When the step is taken by the humanoid, the environment is giving assert not done (from mujoco_env.py) error. When I switched only done condition to false as in v2 everything is working. Stopping the episode when the step is taken is crucial for me. How can I modify done condition without assertion error? When I remove assert not done from mujoco_py the env is not working.

**Comment by gkcgvn** [comment]
Ok I solved it :)

**Comment by tyozmen** [comment]
What caused it and how did you solve it?

**Comment by TigerStone93** [comment]
@tyozmen It's because there might be some errors in 2 possible cases.
1. Check `notdone` condition in `YOUR_ENVIRONMENT_NAME.py`
2. Check `pos`, `size`, `fromto` in `YOUR_ENVIRONMENT_NAME.xml`
