### ISSUE TITLE
Problem with installing in a conda env

### ISSUE THREAD

**Issue by henrycharlesworth** [openai/mujoco-py#369]
I had multiple problems when trying to install which I was able to find solutions for, but finally this one has stopped me and I don't know what to do. I'm trying to install within a conda virtual env, and I get the following error:

...
building 'mujoco_py.cymj' extension
  creating /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder
  creating /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7
  creating /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp
  creating /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k
  creating /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k/mujoco-py
  creating /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py
  creating /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/gl
  gcc -pthread -B /home/henry/anaconda3/envs/deepRL/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Imujoco_py -I/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py -I/home/henry/.mujoco/mjpro150/include -I/home/henry/anaconda3/envs/deepRL/lib/python3.7/site-packages/numpy/core/include -I/home/henry/anaconda3/envs/deepRL/include/python3.7m -c /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/cymj.c -o /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/cymj.o -fopenmp -w
  gcc -pthread -B /home/henry/anaconda3/envs/deepRL/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Imujoco_py -I/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py -I/home/henry/.mujoco/mjpro150/include -I/home/henry/anaconda3/envs/deepRL/lib/python3.7/site-packages/numpy/core/include -I/home/henry/anaconda3/envs/deepRL/include/python3.7m -c /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/gl/osmesashim.c -o /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/gl/osmesashim.o -fopenmp -w
  creating /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/lib.linux-x86_64-3.7
  creating /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/lib.linux-x86_64-3.7/mujoco_py
  gcc -pthread -shared -B /home/henry/anaconda3/envs/deepRL/compiler_compat -L/home/henry/anaconda3/envs/deepRL/lib -Wl,-rpath=/home/henry/anaconda3/envs/deepRL/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/cymj.o /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/gl/osmesashim.o -L/home/henry/.mujoco/mjpro150/bin -Wl,-R/home/henry/.mujoco/mjpro150/bin -lmujoco150 -lglewosmesa -lOSMesa -lGL -o /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/lib.linux-x86_64-3.7/mujoco_py/cymj.cpython-37m-x86_64-linux-gnu.so -fopenmp
  /home/henry/anaconda3/envs/deepRL/compiler_compat/ld: cannot find -lGL
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py
  Running setup.py install for mujoco-py ... error
    Complete output from command /home/henry/anaconda3/envs/deepRL/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3s_s3o3k/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wyi7t23y/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Removing old mujoco_py cext /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/cymj_1.50.1.68_37_linuxcpuextensionbuilder_37.so
    running build_ext
    building 'mujoco_py.cymj' extension
    gcc -pthread -B /home/henry/anaconda3/envs/deepRL/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Imujoco_py -I/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py -I/home/henry/.mujoco/mjpro150/include -I/home/henry/anaconda3/envs/deepRL/lib/python3.7/site-packages/numpy/core/include -I/home/henry/anaconda3/envs/deepRL/include/python3.7m -c /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/cymj.c -o /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/cymj.o -fopenmp -w
    gcc -pthread -B /home/henry/anaconda3/envs/deepRL/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Imujoco_py -I/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py -I/home/henry/.mujoco/mjpro150/include -I/home/henry/anaconda3/envs/deepRL/lib/python3.7/site-packages/numpy/core/include -I/home/henry/anaconda3/envs/deepRL/include/python3.7m -c /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/gl/osmesashim.c -o /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/gl/osmesashim.o -fopenmp -w
    gcc -pthread -shared -B /home/henry/anaconda3/envs/deepRL/compiler_compat -L/home/henry/anaconda3/envs/deepRL/lib -Wl,-rpath=/home/henry/anaconda3/envs/deepRL/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/cymj.o /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/gl/osmesashim.o -L/home/henry/.mujoco/mjpro150/bin -Wl,-R/home/henry/.mujoco/mjpro150/bin -lmujoco150 -lglewosmesa -lOSMesa -lGL -o /tmp/pip-install-3s_s3o3k/mujoco-py/mujoco_py/generated/_pyxbld_1.50.1.68_37_linuxcpuextensionbuilder/lib.linux-x86_64-3.7/mujoco_py/cymj.cpython-37m-x86_64-linux-gnu.so -fopenmp
    /home/henry/anaconda3/envs/deepRL/compiler_compat/ld: cannot find -lGL
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1

Anyone got any ideas? I had literally the exact same issue when I tried to install on another PC too...

**Comment by jaggernaut007** [comment]
This issue is solved here. This worked for me!
https://github.com/openai/mujoco-py/issues/341
