### ISSUE TITLE
Ubuntu 16.04 LTS pip3 compilation error

### ISSUE THREAD

**Issue by minosniu** [openai/mujoco-py#375]
**Describe the bug**
A compilation error that's not related to LD_LIBRARY_PATH, no mujoco, no license, or other common issues reported elsewhere.

**To Reproduce**
Everything when run pip3 install

**Expected behavior**

**Error Messages**
$ pip3 install -U 'mujoco-py<2.1,>=2.0'Collecting mujoco-py<2.1,>=2.0
  Using cached https://files.pythonhosted.org/packages/9e/ea/3fa08305b80346a787bae7b45eaa8e11d4187f85e012b95ad7bcd97f8336/mujoco-py-2.0.2.0.tar.gz
Requirement already satisfied, skipping upgrade: glfw>=1.4.0 in ./.local/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (1.7.1)
Requirement already satisfied, skipping upgrade: numpy>=1.11 in ./.local/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (1.16.2)
Requirement already satisfied, skipping upgrade: Cython>=0.27.2 in ./.local/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (0.29.6)
Requirement already satisfied, skipping upgrade: imageio>=2.1.2 in ./.local/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (2.5.0)
Requirement already satisfied, skipping upgrade: cffi>=1.10 in ./.local/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (1.12.2)
Requirement already satisfied, skipping upgrade: lockfile>=0.12.2 in ./.local/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (0.12.2)
Requirement already satisfied, skipping upgrade: pillow in ./.local/lib/python3.6/site-packages (from imageio>=2.1.2->mujoco-py<2.1,>=2.0) (5.4.1)
Requirement already satisfied, skipping upgrade: pycparser in ./.local/lib/python3.6/site-packages (from cffi>=1.10->mujoco-py<2.1,>=2.0) (2.19)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (setup.py) ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lorp7dkb/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-cw6acq7m --python-tag cp36:
  running bdist_wheel
  running build
  Removing old mujoco_py cext /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/generated/cymj_2.0.2.0_36_linuxcpuextensionbuilder_36.so
  Compiling /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/cymj.pyx because it depends on /home/neuromorphic/.local/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd.
  [1/1] Cythonizing /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/cymj.pyx
  running build_ext
  building 'mujoco_py.cymj' extension
  creating /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.0_36_linuxcpuextensionbuilder
  creating /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.0_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6
  creating /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.0_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp
  creating /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.0_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-lorp7dkb
  creating /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.0_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-lorp7dkb/mujoco-py
  creating /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.0_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py
  creating /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.0_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/gl
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imujoco_py -I/tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py -I/home/neuromorphic/.mujoco/mujoco200/include -I/home/neuromorphic/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/cymj.c -o /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.0_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/cymj.o -fopenmp -w
  /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/cymj.c:54:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py
  Running setup.py install for mujoco-py ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lorp7dkb/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ljth_d5_/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Removing old mujoco_py cext /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/generated/cymj_2.0.2.0_36_linuxcpuextensionbuilder_36.so
    running build_ext
    building 'mujoco_py.cymj' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imujoco_py -I/tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py -I/home/neuromorphic/.mujoco/mujoco200/include -I/home/neuromorphic/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/cymj.c -o /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.0_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/cymj.o -fopenmp -w
    /tmp/pip-install-lorp7dkb/mujoco-py/mujoco_py/cymj.c:54:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lorp7dkb/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ljth_d5_/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-lorp7dkb/mujoco-py/

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Python Version 3.6.7
 - Mujoco Version 200
 - mujoco-py version 2.1.2

**Environment**
 - output of: `echo $LD_LIBRARY_PATH`
:/home/neuromorphic/.mujoco/mujoco200/bin:/home/neuromorphic/.mujoco/mujoco200/bin

**Comment by MillionIntegrals** [comment]
Looks like you need to install development headers for your python installation, package is probably called `libpython3-dev` or something similar on Ubuntu.
