### ISSUE TITLE
Segmentation fault installing mujoco-py

### ISSUE THREAD

**Issue by fuchuyuan** [openai/mujoco-py#387]
I'm getting a segfault installing mujoco-py when executing:
pip3 install -U 'mujoco-py<2.1,>=2.0'

Log:

`Collecting mujoco-py<2.1,>=2.0
Collecting cffi>=1.10 (from mujoco-py<2.1,>=2.0)
  Using cached https://files.pythonhosted.org/packages/20/f7/87b62a8895bf7c93e907b05b97bc4459c81a38a61151f03a6eae13d863aa/cffi-1.12.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting glfw>=1.4.0 (from mujoco-py<2.1,>=2.0)
Collecting lockfile>=0.12.2 (from mujoco-py<2.1,>=2.0)
  Using cached https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting imageio>=2.1.2 (from mujoco-py<2.1,>=2.0)
  Using cached https://files.pythonhosted.org/packages/af/0a/943c965d372dae0b1f1482677d29030ab834351a61a9a632fd62f27f1523/imageio-2.5.0-py3-none-any.whl
Collecting Cython>=0.27.2 (from mujoco-py<2.1,>=2.0)
  Using cached https://files.pythonhosted.org/packages/b2/20/46a78072ecd4fda072c3791a257b03af99b64673671663067d18bc4935ec/Cython-0.29.7-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy>=1.11 (from mujoco-py<2.1,>=2.0)
  Using cached https://files.pythonhosted.org/packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.10->mujoco-py<2.1,>=2.0)
Collecting pillow (from imageio>=2.1.2->mujoco-py<2.1,>=2.0)
  Using cached https://files.pythonhosted.org/packages/d2/c2/f84b1e57416755e967236468dcfb0fad7fd911f707185efc4ba8834a1a94/Pillow-6.0.0-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: pycparser, cffi, glfw, lockfile, pillow, numpy, imageio, Cython, mujoco-py
Successfully installed Cython-0.29.7 cffi-1.12.2 glfw-1.7.1 imageio-2.5.0 lockfile-0.12.2 mujoco-py-2.0.2.1 numpy-1.16.2 pillow-6.0.0 pycparser-2.19
Segmentation fault`

**Comment by sholtodouglas** [comment]
I found that using pip instead of pip3 worked - and on my computer they both link to the same python version so it was fine.
