### ISSUE TITLE
Error in Building Wheels and "You appear to be missing MuJoCo" for Mac mujoco-py version 1.50.2

### ISSUE THREAD

**Issue by weijiafeng** [openai/mujoco-py#410]
Hi all~,

When I tried to install Mujoco-py it keeps on getting the error: "**Building wheel for mujoco-py (setup.py) ...**" error and "**You appear to be missing MuJoCo. We expected to find the file here: /Users/maggiefeng/.mujoco/mujoco200**". but I have clearly put the mujoco files in the described folder:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/40955107/58565729-ce887a00-8261-11e9-8e10-dc32613268b2.png">

I've tried most of the solutions from past posts but haven't succeeded yet with version 1.50.2. When I install Mujoco-py 0.5.7 it can be installed successfully, but for some tasks, 0.5.7 is not enough.

FYI - My environment is:

MacOS Mojave version 10.14.1
Python 3.5.2
Gym version I am not sure but I tried version 0.9 (but never succeeded overall)

Note: in the screenshot below, though I downgraded to python 3.5.2, the installed Mujoco-py 0.5.7 is still in the Python 3.7 library, not sure if this is an issue? Thank you very much for your help!

<img width="803" alt="image" src="https://user-images.githubusercontent.com/40955107/58565518-7baec280-8261-11e9-8710-842fe4ddf16a.png">

**Comment by caprest** [comment]
it seems like you have to put the mujoco library at `.mujoco` folder instead of `mujoco` folder.
Check the output of  `ls /Users/maggiefeng/.mujoco` to verify the library is properly placed.

**Comment by weijiafeng** [comment]
@caprest Yep it works following what you said, thank you very much! :-)

**Comment by zueting** [comment]
Hello,
I encounter the same problem. But I am having trouble create the .folder in mac. How did you do it?

**Comment by weijiafeng** [comment]
@zueting use Mac terminal's command line to create the folder, since folders starting with "." are "invisible" in the folder view, you need to create and view details in the folder via command line

**Comment by zueting** [comment]
Thanks for your help

**Comment by CS309** [comment]
@weijiafeng I think I am having the same problem.
How do I create and view details in the folder via command line, like you say? I tried renaming the folder in terminal using "mv folder .folder" but I got this back: "mv: rename folder to .folder: Not a directory". 

Next, I tried unzipping my file into .folder (I had already unzipped it into the original folder), and got this back: 
"Archive:  /Users/myname/Downloads/myfile.zip
checkdir:  cannot create extraction directory: .folder
           File exists"

Finally, I tried creating .folder with "mkdir .folder" and got back 
"mkdir: .folder: File exists"

Please help!

**Comment by CS309** [comment]
When I try "mkdir Users/myname/.folder"

I get back "mkdir: Users/myname: No such file or directory"

As background info, I am on macos.

**Comment by IndupriyaKompi** [comment]
I tried this and it worked.

1. mkdir ./mujoco
2. cd ./mujoco
3. download/copy/move mujoco200 here
