### ISSUE TITLE
compile.cpp Compile Error(for using urdf model)

### ISSUE THREAD

**Issue by tuonan** [openai/mujoco-py#422]
I want to use compile.cpp for transforming urdf model to .mjb format.
I use "g++ compile.cpp -o compile"：
/tmp/ccEOWRqn.o: In function `finish(char const*, _mjModel*)':
compile.cpp:(.text+0x1f): undefined reference to `mj_deleteModel'
compile.cpp:(.text+0x24): undefined reference to `mj_deactivate'
/tmp/ccEOWRqn.o: In function `main':
compile.cpp:(.text+0x243): undefined reference to `mj_activate'
compile.cpp:(.text+0x33b): undefined reference to `mj_loadXML'
compile.cpp:(.text+0x35f): undefined reference to `mj_loadModel'
compile.cpp:(.text+0x3d8): undefined reference to `mj_saveLastXML'
compile.cpp:(.text+0x42c): undefined reference to `mj_saveModel'
compile.cpp:(.text+0x44e): undefined reference to `mj_printModel'
collect2: error: ld returned 1 exit status

**Comment by MillionIntegrals** [comment]
Most likely you need to link mujoco libraries?
