### ISSUE TITLE
Does mujoco-py support manipulating soft bodies?

### ISSUE THREAD

**Issue by imankgoyal** [openai/mujoco-py#446]
Hi,
I find the mojoco-py framework very cool. Does it support manipulating soft objects like cloth, ropes? As far as I understand, mujoco does support soft object manipulation. Does that support come out-of-the-box for mujoco-py? If not then any ideas on how to do it?
Thanks!

**Comment by MillionIntegrals** [comment]
mujoco-py is a very thin layer over mujoco, so in general whatever mujoco supports mujoco-py also does. The best way to learn about it is from the mujoco documentation http://www.mujoco.org/book/index.html

**Comment by imankgoyal** [comment]
Thanks for the clarification.
