### ISSUE TITLE
cannot import mujoco_py 1.50.1.0 using python 3.6.1 in windows

### ISSUE THREAD

**Issue by zemus-lab** [openai/mujoco-py#521]
I've been reading many issues related to importing mujoco_py, but I just can't seem to solve it.

I just get the following error:
 raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat

Can somebody help me? I'm getting desperate.

I installed it from the source file using python setup.py install

**Comment by Aafiya-H** [comment]
Hi @zemus-lab! Have you been able to resolve the issue? If so, what method worked for you?
