### ISSUE TITLE
collision margin in mujoco

### ISSUE THREAD

**Issue by v-wewei** [openai/mujoco-py#587]
how to set the collision margin in mujoco-py?

**Comment by codeFairOfficial** [comment]
@v-wewei it looks like no one is answering this question :disappointed: . My name is Matt and I work for a compnay named codeFair that is trying to help get issues/questions resolved quickly. One of our developers has worked with mujocopy in the past and can get this question answered for you, we just need you to fill out the following form: https://sahchhnmtaj.typeform.com/to/nB94H3p1

**Comment by v-wewei** [comment]
got solved
