### ISSUE TITLE
link in readme outofdate

### ISSUE THREAD

**Issue by lsqshr** [openai/mujoco-py#6]
Obtain a 30-day free trial on the MuJoCo website: 'https://www.roboti.us/trybuy.html'. The license key will arrive in an email with your username and password.

The link here is outofdate

**Comment by PaganBlasphemer** [comment]
Looks to currently be https://www.roboti.us/license.html for trial
signups.  If I knew how to use github I'd fix it myself...

You must be the change you wish to see in the world.

**Comment by gdb** [comment]
Thanks!
