### ISSUE TITLE
Release v2.1.0

### ISSUE THREAD

**Issue by paantya** [openai/mujoco-py#648]
PLS creat Release v2.1.0

**Comment by wookayin** [comment]
@paantya Regarding https://github.com/openai/mujoco-py/issues/642#issuecomment-963889665, you just have to follow what you see in the error message:
```
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.mujoco/mujoco210/bin
```

I am leaving my comment here because your comment in #642 is off-topic.

**Comment by matthiasplappert** [comment]
This is now released on PyPI.

**Comment by wookayin** [comment]
@matthiasplappert Thanks for releasing the package. It would be also great to push a tag/release to github.

**Comment by matthiasplappert** [comment]
good point, done
