### ISSUE TITLE
Unexpected file size in image file 

### ISSUE THREAD

**Issue by modpy44** [openai/mujoco-py#688]
I am trying to add a png image as texture, I got this error when simulating the model:
`Error: unexpected file size in file '/textures/logo.jpg' `
Any ideas ?

**Comment by modpy44** [comment]
Cube texture images faces must be all square and with the same size

**Comment by cidxb** [comment]
> Cube texture images faces must be all square and with the same size

Hi， i run into the same problem too, how I could fix this problem?
