### ISSUE TITLE
Mujoco key path naming discrepancy

### ISSUE THREAD

**Issue by neocxi** [openai/mujoco-py#7]
In `config.py` an environment variable named "MUJOCO_PY_MJ_key_path" is used to get the path to mujoco key file (https://github.com/openai/mujoco-py/blob/master/mujoco_py/config.py#L17) but it's described to be "MUJOCO_PY_MJKEY_PATH" in README.

I think changing the environment to "MUJOCO_PY_MJKEY_PATH" will make it more consistent but will probably break some existing setups. If we have a consensus on how to proceed, I'm happy to open an PR to fix it.

**Comment by gdb** [comment]
Hah, whoops. Yep, let's fix that to MUJOCO_PY_MJKEY_PATH.

We can just change it without thinking that hard (I think few people if anyone use the environment variables — no one's complained about `MUJOCO_PY_MJKEY_PATH` not working), and bump the minor version.
