### ISSUE TITLE
Non-holonimic contstraints in py-mujoco/mujoco. It is possible?

### ISSUE THREAD

**Issue by nor-code** [openai/mujoco-py#740]
Hi there! @machinaut @jonasschneider 

Can i described non-holonimic constraints in mujoco?
For example, there are the spherical shell inside which move a wheel. I want that wheel and shell in contact point have the same velocity.
In other word, wheel must move inside shell without slipping.

And as saying in[ documentation ](https://mujoco.readthedocs.io/en/latest/computation.html?highlight=non-holonomic%20constraints#equality):
"The solver can actually work with non-holonomic constraints as well, but we do not yet have such constraint types defined. "
It turns out that there are no tags to describe such constraints? Is there any way to set these constraints?
I would be very grateful if you could give me an example!

pic and equation(v - velocity) below
![Снимок экрана от 2022-08-21 15-11-15](https://user-images.githubusercontent.com/42301816/185793360-789a3fa7-0843-449e-bf11-e12141a76101.png)
![plane_case](https://user-images.githubusercontent.com/42301816/185793451-c13ea806-70a6-4860-b5ff-8f0881e3a495.jpg)

**Comment by YouJiacheng** [comment]
This project is actually unmaintained.
DeepMind, the owner of mujoco, has released their official mujoco python binding in https://github.com/deepmind/mujoco/tree/main/python.
